### ISSUE TITLE
Render plain lists

### ISSUE THREAD

**Issue by darelf** [soranoba/bbmustache#12]
I can't find it in the mustache documentation, but using the demo ( http://mustache.github.io/#demo ) shows that this:

    {{#mylist}}
      {{.}}
    {{/mylist}}

Will work on lists that look like this:

    mylist: ["Item 1", "Item 2", "Item 3"]

Producing output like this:

    Item 1
    Item 2
    Item 3

I was hoping that an erlang map that looked like this:

    #{ "mylist" => ["Item 1", "Item 2", "Item 3"] }

would allow the same behavior, but it seems to be unsupported.

**Comment by soranoba** [comment]
Thank you @darelf . I did not know this.

As a result of look at the mustache implementation of many languages, I was able to confirm its implementation in many languages. (e.g. bash, golang, c++, ....)
So, I'm going to add this feature to the bbmustache.

However, please wait a few days, because there are things I want to consider some.
If you want to use in a hurry, please refer to [here](https://github.com/soranoba/bbmustache/tree/feature/dot-operator).

**Comment by darelf** [comment]
This feature branch version almost works.

It fails at escaping syntax, like this:

    {{#mylist}}
      {{{.}}}
    {{/mylist}}

It gives the error:

    no function clause matching proplists:get_value(<<".">>, <<"Item 1">>, <<>>)

**Comment by soranoba** [comment]
Oops....

Sorry, I fix this and update [the document](https://github.com/soranoba/bbmustache/tree/2c36cb36581a1c90f07eb4ced5052255b15e9373#undocumented-function).

**Comment by darelf** [comment]
Make sure to also handle the binary version in your `data_get/3` function

**Comment by soranoba** [comment]
Oh... =(

[I fixed it, now.](https://github.com/soranoba/bbmustache/compare/2c36cb36581a1c90f07eb4ced5052255b15e9373...d41ae709af0c76d2e62bdb2b5acfe723f1167d7d) Thank you for pointing out to me.

**Comment by soranoba** [comment]
https://github.com/soranoba/bbmustache/releases/tag/v1.1.0

I was released v1.1.0.
it contains this issue and a minor modification.
