### ISSUE TITLE
Tag lookup doesn't descend the context stack

### ISSUE THREAD

**Issue by bjn-jbrinkley** [soranoba/bbmustache#17]
Given the following map:

    Map = #{
       "author" => "Bill",
       "os" => [
          #{ "name" => "Ubuntu", "version" => "12" },
          #{ "name" => "Ubuntu", "version" => "16" }
       ] }.

And the following template:

    Tmpl = <<"Author: {{author}}, OSes: {{#os}}{{name}}/{{version}} ({{author}}) {{/os}}">>.

The following result is in error:

    1> bbmustache:render(Tmpl, Map).
    <<"Author: Bill, OSes: Ubuntu/12 () Ubuntu/16 () ">>

The output should be `<<"Author: Bill, OSes: Ubuntu/12 (Bill) Ubuntu/16 (Bill) ">>`.

**Comment by soranoba** [comment]
@bjn-jbrinkley 

Thank you for this issue.

I am aware of this issue, but I have not yet able to correspond.
I'm sorry, please wait until the corresponding. =(

Corresponding spec is disclosed in the following.
https://github.com/soranoba/bbmustache/tree/v1.3.0/benchmarks

This problem is `Deeply Nested Contexts`.
- https://github.com/mustache/spec/blob/v1.1.3/specs/sections.yml#L56-L93
- https://github.com/soranoba/bbmustache/tree/v1.3.0/benchmarks#sections

**Comment by soranoba** [comment]
This issue has been resolved on v1.4.0.
If there is a shortage, please report in this issue or a new issue !!

**Comment by bjn-jbrinkley** [comment]
Thanks for fixing so quickly! I'll open a new issue if there are any problems.
