### ISSUE TITLE
Bug?  intra-tag whitespace not rendering

### ISSUE THREAD

**Issue by amorphid** [soranoba/bbmustache#20]
(in Elixir...)

A tag with a space in the middle doesn't get rendered.  Is this intentional, or a bug?
```
iex(12)> :bbmustache.render("{{foo bar}}", [{'foo bar', "potato"}]) 
""
```
I can't find any thing in the Mustache docs about white space being disallowed.

**Comment by soranoba** [comment]
Hi @amorphid . Thank you for report.

It is the intentional and Its behavior is from v1.2.0.
Please refer to https://github.com/soranoba/bbmustache/issues/14
>  If the tag including the space has been specified, it became to delete the space.
> 💡 Tag MUST NOT include the spaces. The current behavior is likely to change in the future.

The specification of mustache has the following sentences.

>   The tag's content MUST be a non-whitespace character sequence NOT containing the current closing delimiter.

https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L4-L5

----

I was struggling for the existence of space when turning on the function of `A.B.C`.
Does the meaning of` A . B . C` be the same as `A.B.C`? 
What about `A .. B. C`?

I chose to fulfill the specifications by erasing the space between them.

Of course, I do not think this is the best.
However, using spaces in tags than that is not recommended as it is highly likely to cause implementation dependent behavior of the library.

This is the background of its behaviour.
