### ISSUE TITLE
Fix documentation link on Hexpm

### ISSUE THREAD

**Issue by yordis** [soranoba/bbmustache#24]
When I click on Documentation the link is broken.

**Comment by soranoba** [comment]
The bbmustache document is output with markdown.
Because of that, it could not handle it with hex.pm, and I can not delete the link created at 1.0.0.

Please tell me the way if you know.

If you just want to know the location of the document, please look at links below.
- [documentation of bbmustache](https://github.com/soranoba/bbmustache/blob/master/doc/bbmustache.md)
- [man page of mustache](http://mustache.github.io/mustache.5.html)
- [specification of mustache](https://github.com/mustache/spec)
- [Functions supported by bbmustache](https://github.com/soranoba/bbmustache/blob/master/benchmarks/README.md#check-the-reference-implementation)

**Comment by yordis** [comment]
@soranoba maybe is better to bring somebody from hex team so they could help about it?

P.S: Thanks a lot for the documentation link.

**Comment by soranoba** [comment]
Delete of documents was already supported with the latest [rebar 3_hex](https://github.com/tsloughter/rebar3_hex).
And, I was delete link of the document.

Thanks a lot.
