### ISSUE TITLE
Allow array access for lists

### ISSUE THREAD

**Issue by evan-gordon** [soranoba/bbmustache#41]
Hey,

Currently i have need to use the mustache array index functionality.

Currently if i run:
```erlang
1> bbmustache:render(<<"check out my template: {{a.1}}">>, #{"a" => ["foo", "bar"]})
<<"check out my template: ">>
```
From what i understand from mustache we should see:
```erlang
1> bbmustache:render(<<"check out my template: {{a.1}}">>, #{"a" => ["foo", "bar"]})
<<"check out my template: foo">>
```

From looking around online both `.1.` and `.[1].` seem to be a supported syntax in most libraries, though the former seems more common to me.

I've got a PR that I can put up with the fix for this if you it's decided to be a good addition to the library.

**Comment by soranoba** [comment]
Hi, @evan-gordon 
Can you tell me some libraries that support this syntax?

**Comment by evan-gordon** [comment]
sure!

It seems like mustache JS does:
https://github.com/janl/mustache.js/issues/158 

https://github.com/samskivert/jmustache/pull/44

this seems to be a popular stackoverflow issue on the topic:
https://stackoverflow.com/questions/11147373/only-show-the-first-item-in-list-using-mustache/17950970#17950970
they suggest that handlebars.js supports the `.[0].` synatax.

It looks like mustache.java supports it, but as an extension (not too sure what that means)
https://github.com/spullara/mustache.java/issues/68

Most libraries (and the mustache spec) don't seem to document it though so it's hard to find more information than this.

**Comment by soranoba** [comment]
Thank you for the information.
I will check and decide, so please wait for a few days. 🙇

**Comment by evan-gordon** [comment]
Sure, no worries.

For reference if you want to see what the changes would look like check here:
https://github.com/evan-gordon/bbmustache/commit/b43a502b14800a652f0098dba42e5154c2f3ff33

Fyi, this is the `.0.` index implementation.

Forgive my erlang if it's not very good, I use Elixir typically.

**Comment by soranoba** [comment]
https://github.com/mustache/mustache/issues/222#issuecomment-219985169

As far as I looked into it, as Ricardo said in this comment, I think that this behavior depends on the implementation of javascript.

- I am negative about adding syntax, because it possible syntax collision in the future.
- Some libraries have similar issues, but many of them are not solved.
  - mustache/mustache: https://github.com/mustache/mustache/issues/222
  - defunkt/pystache: https://github.com/defunkt/pystache/issues/196
  - groue/GRMustache.swift: https://github.com/groue/GRMustache.swift/issues/2
- It currently supports assoc list, so it is difficult to prioritize array and assoc list.
  - If data is `[{"a", [{"0", "value"}]}]`, it is difficult to determine whether `a.0` refers to `"value"` or `{"0", "value"}`.

For these reasons, I will avoid official support.

----

FYI:
I put a patch I wrote, because I am worry about the performance waste of your implementation.
https://gist.github.com/soranoba/2d0c53b3c293beb011f5a2fcbe961648

**Comment by evan-gordon** [comment]
Yeah i was aware of the support for assoc lists, and i thought of adding a flag for possibly enabling this feature as it's something i have to support.

Thanks for the patch i appreciate it! Though I'm sad to hear this won't be officcially supported. 
I'll close the ticket then.
