### ISSUE TITLE
Variable test not matching spec

### ISSUE THREAD

**Issue by eproxus** [soranoba/bbmustache#67]
Running the [variable test from the spec](https://github.com/mustache/spec/blob/v1.2.2/specs/sections.yml#L68-L75) results in something I didn't expect:
```
1> bbmustache:render(<<"\"{{#foo}}{{.}} is {{foo}}{{/foo}}\"">>, #{"foo" => "bar"}).
<<"\"98 is bar97 is bar114 is bar\"">>
```

I was expecting the result `<<"\"bar is bar\"">>`. Perhaps I'm missing something or is this a bug?

**Comment by soranoba** [comment]
Hi @eproxus ,

It is not a bug.
In Erlang, lists and strings are indistinguishable.
Therefore, there is no choice but to make an analogy.

Since section (`{{# section}}`) is often expected to be an array, bb mustache thinks it's likely an array.
The easiest way to get this to work correctly is to use binary instead of string.

```
1> bbmustache:render(<<"\"{{#foo}}{{.}} is {{foo}}{{/foo}}\"">>, #{"foo" => <<"bar">>}).
<<"\"bar is bar\"">>
2> bbmustache:render(<<"\"{{#foo}}{{.}} is {{foo}}{{/foo}}\"">>, #{<<"foo">> => <<"bar">>}, [{key_type, binary}]).
<<"\"bar is bar\"">>
```

Of course, If you know a good solution, I can consider it if you can suggest it. =)

**Comment by eproxus** [comment]
Got it, that makes sense. Came across it in Rebar, will propose a fix there.

**Comment by eproxus** [comment]
There is `io_lib:printable_list(Term) -> true | false` but I think that would be too slow to call on each list value when rendering . And if you do that, you might as well call `iolist_to_binary(Term)` on everything you know is a string.

**Comment by soranoba** [comment]
Thank you for the information =)
